server:
  port: 8080

spring:
  application:
    name: caching-demo
  
  datasource:
    url: jdbc:mysql://mysql:3306/cache_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
  flyway:
    url: jdbc:mysql://mysql:3306/caching_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: root
    password: root
    baseline-on-migrate: true
    
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sunlife.demo: INFO
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cache:
  ttl-minutes: 30
  
memcached:
  servers: memcached:11211
  
hazelcast:
  persistence:
    enabled: true
    base-dir: /tmp/hazelcast-data
